â–ˆ>>> Traceback (most recent call last):
  File "chatter2AllPerson.py", line 169, in <module>
    embed()
  File "/home/wangsai/wxRobot/lib/python3.5/site-packages/wxpy/utils/console.py", line 74, in embed
    _shell(local=local, banner=banner)
  File "/home/wangsai/wxRobot/lib/python3.5/site-packages/wxpy/utils/console.py", line 43, in _python
    code.interact(local=local, banner=banner)
  File "/usr/lib/python3.5/code.py", line 292, in interact
    console.interact(banner)
  File "/usr/lib/python3.5/code.py", line 223, in interact
    line = self.raw_input(prompt)
  File "/usr/lib/python3.5/code.py", line 266, in raw_input
    return input(prompt)
OSError: [Errno 9] Bad file descriptor
â–ˆPlease press confirm on your phone.
Loading the contact, this may take a little while.
[H[2JLogin successfully as Sai.W
>>> Traceback (most recent call last):
  File "chatter2AllPerson.py", line 169, in <module>
    embed()
  File "/home/wangsai/wxRobot/lib/python3.5/site-packages/wxpy/utils/console.py", line 74, in embed
    _shell(local=local, banner=banner)
  File "/home/wangsai/wxRobot/lib/python3.5/site-packages/wxpy/utils/console.py", line 43, in _python
    code.interact(local=local, banner=banner)
  File "/usr/lib/python3.5/code.py", line 292, in interact
    console.interact(banner)
  File "/usr/lib/python3.5/code.py", line 223, in interact
    line = self.raw_input(prompt)
  File "/usr/lib/python3.5/code.py", line 266, in raw_input
    return input(prompt)
OSError: [Errno 9] Bad file descriptor
